export interface Project {
  id: number,
  imageSrc: string,
  title: string,
  preview: string,
  description: string,
  link: string,
  linkText: string,
  viewHeight: number,
  firstParagraph: string,
  secondParagraph: string,
  ulElements: string[],
  olElements: string[],
  thirdParagraph: string,
  videoSrc: string,
}
