name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build 

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to SSH server
      uses: webfactory/ssh-agent@v0.8.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          ls -la
          mkdir hello_workd
          cd public_html
          mkdir hello_world
          # rm -rf *
          # cp -r $GITHUB_WORKSPACE/dist/portfolio/* .
        timeout: 2m

