name: Deploy to SSH Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to SSH Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i ~/.ssh/id_rsa milan@skynet.skynet.ie  
# echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
# chmod 600 ~/.ssh/id_rsa
# scp -v -r ./* milan@skynet.skynet.ie:/
# scp -r ./* milan@skynet.skynet.ie:/
