name: Deploy to SSH Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build --prod

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Copy Files to SSH Server
      uses: appleboy/scp-action@v0.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: dist
        target: /path/to/destination
        strip_components: 1
